-- SELECT c.TABLE_NAME Fld_Tlb_Name,c.COLUMN_NAME  Fld_Column_Name,c.DATA_TYPE Fld_Column_Type,DATA_LENGTH Fld_Column_Len,DATA_PRECISION,c.DATA_SCALE Data_Scale,k.POSITION Fld_PK FROM ALL_TAB_COLUMNS c, (SELECT C2.TABLE_NAME,C2.COLUMN_NAME,C2.POSITION FROM USER_CONSTRAINTS C1,USER_CONS_COLUMNS C2 WHERE C1.CONSTRAINT_NAME=C2.CONSTRAINT_NAME AND C1.TABLE_NAME='TJRB' AND C1.CONSTRAINT_TYPE='P') k  WHERE c.TABLE_NAME = k.TABLE_NAME(+) AND c.COLUMN_NAME = k.COLUMN_NAME(+) AND c.OWNER = 'TICKET' AND c.TABLE_NAME='TJRB' ORDER BY c.TABLE_NAME, c.COLUMN_ID;

-- SELECT C2.COLUMN_NAME,C2.POSITION FROM ALL_CONSTRAINTS C1,ALL_CONS_COLUMNS C2 WHERE C1.CONSTRAINT_NAME=C2.CONSTRAINT_NAME AND C1.TABLE_NAME='ALL_CONSTRAINTS' AND C1.CONSTRAINT_TYPE='P';

-- SELECT TABLE_NAME,COLUMN_NAME,COLUMN_POSITION,INDEX_NAME FROM  ALL_IND_COLUMNS WHERE TABLE_NAME='ALL_CONSTRAINTS' AND INDEX_NAME=(SELECT INDEX_NAME FROM ALL_INDEXES WHERE TABLE_NAME='ALL_CONSTRAINTS' AND UNIQUENESS='UNIQUE');

SELECT INDEX_NAME,UNIQUENESS FROM USER_INDEXES WHERE TABLE_NAME='USER_CONS_COLUMNS';

