create table user_hww(
id number(4) primary key,
username varchar2(20) not null,
password varchar2(20) not null,
email varchar2(50) not null
);

create sequence seq_ticket increment by 1 start with 1;

insert into user_hww(id, username, password, email) values(seq_ticket.nextval, 'hww', 'hww', 'huangwwjp@gmail');

create table stopstation_hww(
id number(4) primary key, 
trainno varchar2(12) not null,
seq number(4) not null,
stationcode varchar2(30) not null,
stationname varchar2(30) not null
);

insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '2400000D3107', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '2400000D3107', '02', 'TXP', '天津西'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '2400000D3107', '03', 'TAK', '泰山  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '2400000D3107', '04', 'YZK', '兖州  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '2400000D3107', '05', 'XCH', '徐州  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '2400000D3107', '06', 'BBH', '蚌埠  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '2400000D3107', '07', 'NJH', '南京  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '2400000D3107', '08', 'SHH', '上海  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '2400000D3501', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '2400000D3501', '02', 'TXP', '天津西'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '2400000D3501', '03', 'DZP', '德州  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '2400000D3501', '04', 'JNK', '济南  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '2400000D3710', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '2400000D3710', '02', 'TXP', '天津西'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '2400000D3710', '03', 'JNK', '济南  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '2400000D4102', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '2400000D4102', '02', 'TXP', '天津西'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '2400000D4102', '03', 'COP', '沧州  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '2400000D4102', '04', 'DZP', '德州  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '2400000D4102', '05', 'JNK', '济南  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '2400000D5106', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '2400000D5106', '02', 'TXP', '天津西'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '2400000D5106', '03', 'DZP', '德州  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '2400000D5106', '04', 'ZBK', '淄博  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '2400000D5106', '05', 'WFK', '潍坊  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '2400000D5106', '06', 'QDK', '青岛  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '2400000D5300', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '2400000D5300', '02', 'TXP', '天津西'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '2400000D5300', '03', 'DZP', '德州  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '2400000D5300', '04', 'ZBK', '淄博  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '2400000D5300', '05', 'WFK', '潍坊  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '2400000D5300', '06', 'QDK', '青岛  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '2400000D5504', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '2400000D5504', '02', 'TXP', '天津西'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '2400000D5504', '03', 'DZP', '德州  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '2400000D5504', '04', 'ZBK', '淄博  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '2400000D5504', '05', 'WFK', '潍坊  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '2400000D5504', '06', 'QDK', '青岛  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '2400000D5700', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '2400000D5700', '02', 'TXP', '天津西'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '2400000D5700', '03', 'COP', '沧州  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '2400000D5700', '04', 'DZP', '德州  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '2400000D5700', '05', 'QZK', '青州市'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '2400000D5700', '06', 'GMK', '高密  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '2400000D5700', '07', 'QDK', '青岛  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '2400000D5903', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '2400000D5903', '02', 'TXP', '天津西'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '2400000D5903', '03', 'DZP', '德州  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '2400000D5903', '04', 'ZBK', '淄博  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '2400000D5903', '05', 'WFK', '潍坊  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '2400000D5903', '06', 'QDK', '青岛  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '2400000D6100', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '2400000D6100', '02', 'TXP', '天津西'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '2400000D6100', '03', 'DZP', '德州  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '2400000D6100', '04', 'ZBK', '淄博  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '2400000D6100', '05', 'WFK', '潍坊  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '2400000D6100', '06', 'QDK', '青岛  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '240000D55700', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '240000D55700', '02', 'TXP', '天津西'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '240000D55900', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '240000D55900', '02', 'TXP', '天津西'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C200101', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C200101', '02', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '250000D55800', '01', 'TXP', '天津西'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '250000D55800', '02', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '250000D56000', '01', 'TXP', '天津西'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '250000D56000', '02', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C200201', '01', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C200201', '02', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '4700000D3610', '01', 'JNK', '济南  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '4700000D3610', '02', 'DZP', '德州  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '4700000D3610', '03', 'TXP', '天津西'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '4700000D3610', '04', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '4700000D3810', '01', 'JNK', '济南  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '4700000D3810', '02', 'TXP', '天津西'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '4700000D3810', '03', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '4700000D4000', '01', 'JNK', '济南  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '4700000D4000', '02', 'DZP', '德州  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '4700000D4000', '03', 'TXP', '天津西'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '4700000D4000', '04', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '4700000D4210', '01', 'JNK', '济南  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '4700000D4210', '02', 'COP', '沧州  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '4700000D4210', '03', 'TXP', '天津西'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '4700000D4210', '04', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '4900000D5200', '01', 'QDK', '青岛  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '4900000D5200', '02', 'WFK', '潍坊  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '4900000D5200', '03', 'ZBK', '淄博  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '4900000D5200', '04', 'JNK', '***   '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '4900000D5200', '05', 'QNK', '***   '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '4900000D5200', '06', 'DZP', '德州  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '4900000D5200', '07', 'TXP', '天津西'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '4900000D5200', '08', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '4900000D5420', '01', 'QDK', '青岛  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '4900000D5420', '02', 'WFK', '潍坊  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '4900000D5420', '03', 'TXP', '天津西'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '4900000D5420', '04', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '4900000D5610', '01', 'QDK', '青岛  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '4900000D5610', '02', 'WFK', '潍坊  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '4900000D5610', '03', 'TXP', '天津西'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '4900000D5610', '04', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '4900000D5820', '01', 'QDK', '青岛  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '4900000D5820', '02', 'GMK', '高密  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '4900000D5820', '03', 'QZK', '青州市'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '4900000D5820', '04', 'DZP', '德州  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '4900000D5820', '05', 'COP', '沧州  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '4900000D5820', '06', 'TXP', '天津西'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '4900000D5820', '07', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '4900000D6000', '01', 'QDK', '青岛  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '4900000D6000', '02', 'WFK', '潍坊  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '4900000D6000', '03', 'ZBK', '淄博  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '4900000D6000', '04', 'DZP', '德州  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '4900000D6000', '05', 'COP', '沧州  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '4900000D6000', '06', 'TXP', '天津西'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '4900000D6000', '07', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '4900000D6200', '01', 'QDK', '青岛  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '4900000D6200', '02', 'WFK', '潍坊  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '4900000D6200', '03', 'ZBK', '淄博  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '4900000D6200', '04', 'DZP', '德州  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '4900000D6200', '05', 'TXP', '天津西'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '4900000D6200', '06', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '5500000D3230', '01', 'SHH', '上海  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '5500000D3230', '02', 'NJH', '南京  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '5500000D3230', '03', 'BBH', '蚌埠  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '5500000D3230', '04', 'XCH', '徐州  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '5500000D3230', '05', 'YZK', '兖州  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '5500000D3230', '06', 'TAK', '泰山  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '5500000D3230', '07', 'TXP', '天津西'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '5500000D3230', '08', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000000Z504', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000000Z504', '02', 'NJH', '南京  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000000Z504', '03', 'SHH', '上海  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '2400000D3102', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '2400000D3102', '02', 'TXP', '天津西'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '2400000D3102', '03', 'XZK', '徐州  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '2400000D3102', '04', 'BBH', '蚌埠  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '2400000D3102', '05', 'NJH', '南京  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '2400000D3102', '06', 'SHH', '上海  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '2400000D3500', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '2400000D3500', '02', 'DZP', '德州  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '2400000D3500', '03', 'JNK', '济南  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '2400000D3700', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '2400000D3700', '02', 'TXP', '天津西'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '2400000D3700', '03', 'JNK', '济南  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '2400000D4101', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '2400000D4101', '02', 'TXP', '天津西'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '2400000D4101', '03', 'JNK', '济南  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000014610E', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000014610E', '02', 'LFP', '廊坊  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000014610E', '03', 'TXP', '天津西'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000014610E', '04', 'JHP', '静海  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000014610E', '05', 'TUP', '唐官屯'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000014610E', '06', 'QXP', '青县  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000014610E', '07', 'COP', '沧州  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000014610E', '08', 'BZP', '泊头  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000014610E', '09', 'WUP', '吴桥  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000014610E', '10', 'DZP', '德州  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000014610E', '11', 'JNK', '济南  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000014610E', '12', 'TAK', '泰山  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000014610E', '13', 'YZK', '兖州  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000014610E', '14', 'ZIK', '邹城  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000014610E', '15', 'XZK', '徐州  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000014610E', '16', 'OXH', '宿州  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000014610E', '17', 'BBH', '蚌埠  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000014610E', '18', 'CUH', '滁州  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000014610E', '19', 'NJH', '南京  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000014610E', '20', 'ZJH', '镇江  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000014610E', '21', 'CZH', '常州  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000014610E', '22', 'WXH', '无锡  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000014610E', '23', 'SZH', '苏州  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000014610E', '24', 'KSH', '昆山  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000014610E', '25', 'SHH', '上海  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '240000D23100', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '240000D23100', '02', 'YYP', '亦庄  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '240000D23100', '03', 'WNP', '武清  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '240000D23100', '04', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '240000D27100', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '240000D27100', '02', 'YYP', '亦庄  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '240000D27100', '03', 'WNP', '武清  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '240000D27100', '04', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '240000D27300', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '240000D27300', '02', 'YYP', '亦庄  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '240000D27300', '03', 'WNP', '武清  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '240000D27300', '04', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '240000D50900', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '240000D50900', '02', 'YYP', '亦庄  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '240000D50900', '03', 'WNP', '武清  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '240000D50900', '04', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '240000D51100', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '240000D51100', '02', 'YYP', '亦庄  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '240000D51100', '03', 'WNP', '武清  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '240000D51100', '04', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '240000D51300', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '240000D51300', '02', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '240000D51300', '03', 'TGP', '塘沽  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '240000D58100', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '240000D58100', '02', 'YYP', '亦庄  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '240000D58100', '03', 'WNP', '武清  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '240000D58100', '04', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '240000D58300', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '240000D58300', '02', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '240000D58500', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '240000D58500', '02', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '240000K16100', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '240000K16100', '02', 'TXP', '天津西'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '240000K16100', '03', 'COP', '沧州  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '240000K16100', '04', 'DZP', '德州  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '240000K16100', '05', 'JNK', '济南  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '240000K16100', '06', 'TAK', '泰山  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '240000K16100', '07', 'XZK', '徐州  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '240000K16100', '08', 'BBH', '蚌埠  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '240000K16100', '09', 'NJH', '南京  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '240000K16100', '10', 'NIH', '南京西'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '240000T10303', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '240000T10303', '02', 'XZK', '徐州  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '240000T10303', '03', 'ZJH', '镇江  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '240000T10303', '04', 'WXH', '无锡  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '240000T10303', '05', 'SHH', '上海  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '250000D51000', '01', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '250000D51000', '02', 'WNP', '武清  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '250000D51000', '03', 'YYP', '亦庄  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '250000D51000', '04', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '250000D51200', '01', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '250000D51200', '02', 'WNP', '武清  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '250000D51200', '03', 'YYP', '亦庄  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '250000D51200', '04', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '250000D51400', '01', 'TGP', '塘沽  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '250000D51400', '02', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '250000D51400', '03', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '250000D58200', '01', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '250000D58200', '02', 'WNP', '武清  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '250000D58200', '03', 'YYP', '亦庄  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '250000D58200', '04', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '250000D58400', '01', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '250000D58400', '02', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '250000D58600', '01', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '250000D58600', '02', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '2400000D3900', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '2400000D3900', '02', 'TXP', '天津西'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '2400000D3900', '03', 'DZP', '德州  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '2400000D3900', '04', 'JNK', '济南  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '5500000D3240', '01', 'SHH', '上海  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '5500000D3240', '02', 'NJH', '南京  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '5500000D3240', '03', 'BBH', '蚌埠  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '5500000D3240', '04', 'XCH', '徐州  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '5500000D3240', '05', 'YZK', '兖州  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '5500000D3240', '06', 'TAK', '泰山  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '5500000D3240', '07', 'TXP', '天津西'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '5500000D3240', '08', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C200100', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C200100', '02', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C200300', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C200300', '02', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C200500', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C200500', '02', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C200700', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C200700', '02', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C200900', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C200900', '02', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C201100', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C201100', '02', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C201300', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C201300', '02', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C201500', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C201500', '02', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C201700', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C201700', '02', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C201900', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C201900', '02', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C202100', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C202100', '02', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C202300', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C202300', '02', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C202500', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C202500', '02', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C202700', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C202700', '02', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C202900', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C202900', '02', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C203100', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C203100', '02', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C203300', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C203300', '02', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C203500', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C203500', '02', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C203700', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C203700', '02', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C203900', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C203900', '02', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C204100', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C204100', '02', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C204300', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C204300', '02', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C204500', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C204500', '02', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C204700', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C204700', '02', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C204900', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C204900', '02', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C205100', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C205100', '02', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C205300', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C205300', '02', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C205500', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C205500', '02', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C205700', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C205700', '02', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C205900', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C205900', '02', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C206100', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C206100', '02', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C206300', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C206300', '02', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C206500', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C206500', '02', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C206700', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C206700', '02', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C206900', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C206900', '02', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C220100', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C220100', '02', 'WWP', '武清  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C220100', '03', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C220300', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C220300', '02', 'WWP', '武清  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C220300', '03', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C220500', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C220500', '02', 'WWP', '武清  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C220500', '03', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C220700', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C220700', '02', 'WWP', '武清  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C220700', '03', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C220900', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C220900', '02', 'WWP', '武清  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C220900', '03', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C221100', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C221100', '02', 'WWP', '武清  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C221100', '03', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C227100', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C227100', '02', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C227300', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C227300', '02', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C227500', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C227500', '02', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C227700', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C227700', '02', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C227900', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C227900', '02', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C228100', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C228100', '02', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C200200', '01', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C200200', '02', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C200400', '01', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C200400', '02', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C200600', '01', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C200600', '02', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C200800', '01', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C200800', '02', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C201000', '01', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C201000', '02', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C201200', '01', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C201200', '02', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C201400', '01', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C201400', '02', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C201600', '01', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C201600', '02', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C201800', '01', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C201800', '02', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C202000', '01', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C202000', '02', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C202200', '01', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C202200', '02', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C202400', '01', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C202400', '02', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C202600', '01', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C202600', '02', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C202800', '01', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C202800', '02', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C203000', '01', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C203000', '02', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C203200', '01', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C203200', '02', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C203400', '01', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C203400', '02', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C203600', '01', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C203600', '02', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C203800', '01', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C203800', '02', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C204000', '01', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C204000', '02', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C204200', '01', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C204200', '02', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C204400', '01', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C204400', '02', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C204600', '01', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C204600', '02', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C204800', '01', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C204800', '02', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C205000', '01', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C205000', '02', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C205200', '01', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C205200', '02', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C205400', '01', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C205400', '02', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C205600', '01', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C205600', '02', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C205800', '01', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C205800', '02', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C206000', '01', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C206000', '02', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C206200', '01', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C206200', '02', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C206400', '01', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C206400', '02', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C206600', '01', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C206600', '02', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C206800', '01', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C206800', '02', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C207000', '01', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C207000', '02', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C220200', '01', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C220200', '02', 'WWP', '武清  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C220200', '03', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C220400', '01', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C220400', '02', 'WWP', '武清  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C220400', '03', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C220600', '01', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C220600', '02', 'WWP', '武清  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C220600', '03', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C220800', '01', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C220800', '02', 'WWP', '武清  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C220800', '03', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C221000', '01', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C221000', '02', 'WWP', '武清  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C221000', '03', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C221200', '01', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C221200', '02', 'WWP', '武清  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C221200', '03', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C227200', '01', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C227200', '02', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C227400', '01', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C227400', '02', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C227600', '01', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C227600', '02', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C227800', '01', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C227800', '02', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C228000', '01', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C228000', '02', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C228200', '01', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C228200', '02', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C227101', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C227101', '02', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C200102', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C200102', '02', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C200301', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C200301', '02', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C200501', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C200501', '02', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C200701', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C200701', '02', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C200902', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C200902', '02', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C201101', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C201101', '02', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C201301', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C201301', '02', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C201501', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C201501', '02', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C201701', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C201701', '02', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C201901', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C201901', '02', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C202101', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C202101', '02', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C202301', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C202301', '02', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C202501', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C202501', '02', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C202701', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C202701', '02', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C202901', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C202901', '02', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C203101', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C203101', '02', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C203301', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C203301', '02', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C203501', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C203501', '02', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C203701', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C203701', '02', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C203901', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C203901', '02', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C204101', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C204101', '02', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C204301', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C204301', '02', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C204501', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C204501', '02', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C204701', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C204701', '02', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C204901', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C204901', '02', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C205101', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C205101', '02', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C205301', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C205301', '02', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C205501', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C205501', '02', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C205701', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C205701', '02', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C205901', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C205901', '02', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C206101', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C206101', '02', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C206301', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C206301', '02', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C206501', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C206501', '02', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C206701', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C206701', '02', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C206901', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C206901', '02', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C220101', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C220101', '02', 'WWP', '武清  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C220101', '03', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C220301', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C220301', '02', 'WWP', '武清  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C220301', '03', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C220501', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C220501', '02', 'WWP', '武清  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C220501', '03', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C220701', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C220701', '02', 'WWP', '武清  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C220701', '03', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C220901', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C220901', '02', 'WWP', '武清  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C220901', '03', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C221101', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C221101', '02', 'WWP', '武清  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C221101', '03', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C228101', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C228101', '02', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C200202', '01', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C200202', '02', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C200401', '01', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C200401', '02', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C200601', '01', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C200601', '02', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C200802', '01', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C200802', '02', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C201001', '01', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C201001', '02', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C201201', '01', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C201201', '02', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C201401', '01', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C201401', '02', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C201601', '01', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C201601', '02', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C201801', '01', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C201801', '02', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C202001', '01', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C202001', '02', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C202201', '01', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C202201', '02', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C202401', '01', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C202401', '02', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C202601', '01', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C202601', '02', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C202801', '01', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C202801', '02', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C203001', '01', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C203001', '02', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C203201', '01', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C203201', '02', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C203401', '01', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C203401', '02', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C203601', '01', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C203601', '02', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C203801', '01', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C203801', '02', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C204001', '01', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C204001', '02', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C204201', '01', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C204201', '02', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C204401', '01', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C204401', '02', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C204601', '01', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C204601', '02', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C204801', '01', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C204801', '02', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C205001', '01', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C205001', '02', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C205201', '01', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C205201', '02', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C205401', '01', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C205401', '02', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C205601', '01', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C205601', '02', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C205801', '01', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C205801', '02', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C206001', '01', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C206001', '02', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C206201', '01', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C206201', '02', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C206401', '01', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C206401', '02', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C206601', '01', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C206601', '02', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C206801', '01', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C206801', '02', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C207001', '01', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C207001', '02', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C220201', '01', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C220201', '02', 'WWP', '武清  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C220201', '03', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C220401', '01', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C220401', '02', 'WWP', '武清  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C220401', '03', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C220601', '01', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C220601', '02', 'WWP', '武清  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C220601', '03', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C220801', '01', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C220801', '02', 'WWP', '武清  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C220801', '03', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C221001', '01', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C221001', '02', 'WWP', '武清  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C221001', '03', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C221201', '01', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C221201', '02', 'WWP', '武清  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C221201', '03', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C227201', '01', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C227201', '02', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C228201', '01', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C228201', '02', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C207100', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C207100', '02', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C207300', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C207300', '02', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C207500', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C207500', '02', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C207700', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C207700', '02', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C207900', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C207900', '02', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C208100', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C208100', '02', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C208300', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C208300', '02', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C208500', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C208500', '02', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C208700', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C208700', '02', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C208900', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C208900', '02', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C207200', '01', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C207200', '02', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C207400', '01', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C207400', '02', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C207600', '01', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C207600', '02', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C207800', '01', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C207800', '02', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C208000', '01', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C208000', '02', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C208200', '01', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C208200', '02', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C208400', '01', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C208400', '02', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C208600', '01', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C208600', '02', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C208800', '01', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C208800', '02', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C209000', '01', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C209000', '02', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C209800', '01', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C209800', '02', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C227301', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C227301', '02', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C227501', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C227501', '02', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C227701', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C227701', '02', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C227901', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C227901', '02', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C227401', '01', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C227401', '02', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C227601', '01', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C227601', '02', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C227801', '01', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C227801', '02', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C228001', '01', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C228001', '02', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C227302', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C227302', '02', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C227302', '03', 'TGP', '塘沽  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C227502', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C227502', '02', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C227502', '03', 'TGP', '塘沽  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C227702', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C227702', '02', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C227702', '03', 'TGP', '塘沽  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C227902', '01', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C227902', '02', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '24000C227902', '03', 'TGP', '塘沽  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C227402', '01', 'TGP', '塘沽  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C227402', '02', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C227402', '03', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C227602', '01', 'TGP', '塘沽  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C227602', '02', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C227602', '03', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C227802', '01', 'TGP', '塘沽  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C227802', '02', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C227802', '03', 'VNP', '北京南'); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C228002', '01', 'TGP', '塘沽  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C228002', '02', 'TJP', '天津  '); 	
insert into stopstation_hww(id,trainno,seq,stationcode,stationname) values(seq_ticket.nextval, '25000C228002', '03', 'VNP', '北京南'); 

create table train_hww(
id number(4) primary key,
trainno varchar2(20) not null,
runtrainno varchar2(10) not null
);


insert into train_hww(id, trainno, runtrainno) values(seq_ticket.nextval, '2400000D3107', 'D31');  
insert into train_hww(id, trainno, runtrainno) values(seq_ticket.nextval, '2400000D5504', 'D55');  
insert into train_hww(id, trainno, runtrainno) values(seq_ticket.nextval, '2400000D4102', 'D41');  
insert into train_hww(id, trainno, runtrainno) values(seq_ticket.nextval, '2400000D5106', 'D51');  
insert into train_hww(id, trainno, runtrainno) values(seq_ticket.nextval, '240000K16100', 'K161');  
insert into train_hww(id, trainno, runtrainno) values(seq_ticket.nextval, '24000C227302', 'C2273');  
insert into train_hww(id, trainno, runtrainno) values(seq_ticket.nextval, '24000000Z504', 'Z5');  
insert into train_hww(id, trainno, runtrainno) values(seq_ticket.nextval, '2400000D3710', 'D37'); 
insert into train_hww(id, trainno, runtrainno) values(seq_ticket.nextval, '24000014610E', '1461'); 
insert into train_hww(id, trainno, runtrainno) values(seq_ticket.nextval, '4700000D4210', 'D42'); 
